
all : native-code top native-code-library byte-code-library

OCAML_DEFAULT_DIRS = /usr/local/lib/ocaml/site-lib/sqlite3/

LIBS = unix sqlite3 str

SOURCES = sccp.ml

RESULT = sccp

include OCamlMakefile
